# Generated by Django 5.2.8 on 2025-11-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('web_url', models.URLField()),
                ('code_url', models.URLField()),
                ('pro_img', models.ImageField(upload_to='project_image')),
            ],
        ),
    ]
