# Generated by Django 5.2.8 on 2025-11-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifiactes_class',
            name='certificates_name',
            field=models.CharField(default='Certificte', max_length=20),
        ),
    ]
