# Generated by Django 5.2.8 on 2025-11-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0002_certifiactes_class_certificates_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiactes_class',
            name='certifiactes',
            field=models.FileField(upload_to='certificate'),
        ),
    ]
