# Generated by Django 5.2.8 on 2025-11-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0003_alter_certifiactes_class_certifiactes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiactes_class',
            name='certifiactes',
            field=models.FileField(upload_to='Certificates'),
        ),
    ]
