# Generated by Django 5.2.8 on 2025-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0004_alter_certifiactes_class_certifiactes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiactes_class',
            name='certifiactes',
            field=models.FileField(upload_to='all_certificates'),
        ),
        migrations.AlterField(
            model_name='certifiactes_class',
            name='certificates_name',
            field=models.CharField(default='Certificate', max_length=20),
        ),
    ]
