# Generated by Django 5.2.8 on 2025-11-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0005_alter_certifiactes_class_certifiactes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certifiactes_class',
            old_name='certifiactes',
            new_name='certificates',
        ),
    ]
