# Generated by Django 5.2.8 on 2025-11-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0006_rename_certifiactes_certifiactes_class_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifiactes_class',
            name='certificates',
        ),
        migrations.AddField(
            model_name='certifiactes_class',
            name='certificates_img',
            field=models.ImageField(default=1, upload_to='all_certificates'),
            preserve_default=False,
        ),
    ]
