# Generated by Django 5.2.8 on 2025-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Certificates', '0007_remove_certifiactes_class_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifiactes_class',
            name='certificates_name',
        ),
    ]
