# Generated by Django 5.2.8 on 2025-11-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='skills_data',
            new_name='frontend_skills',
        ),
    ]
