# Generated by Django 5.2.8 on 2025-11-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0002_rename_skills_data_frontend_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontend_skills',
            old_name='img_name',
            new_name='frontend_name',
        ),
    ]
