# Generated by Django 5.2.8 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0003_rename_img_name_frontend_skills_frontend_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills_img')),
                ('framework', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills_img')),
                ('lang', models.CharField(max_length=20)),
            ],
        ),
    ]
