# Generated by Django 5.2.8 on 2025-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0004_framework_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills_img')),
                ('database', models.CharField(max_length=20)),
            ],
        ),
    ]
