# Generated by Django 5.2.8 on 2025-11-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0006_dsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills_img')),
                ('deploy', models.CharField(max_length=20)),
            ],
        ),
    ]
