# Generated by Django 5.2.8 on 2025-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0007_deploy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='image',
            field=models.ImageField(upload_to='deploy_img'),
        ),
    ]
