# Generated by Django 5.2.8 on 2025-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skills', '0008_alter_deploy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='image',
            field=models.ImageField(upload_to='skills_img'),
        ),
    ]
